development:
  adapter: postgresql
  encoding: unicode
  database: UI_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: 
  password:
